// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAab9lfv-W8r3LLCOUlmvj00nV_74jGW20',
    appId: '1:1068725299615:web:16c9377c9330af1075b5aa',
    messagingSenderId: '1068725299615',
    projectId: 'software-engineering-pro-21553',
    authDomain: 'software-engineering-pro-21553.firebaseapp.com',
    storageBucket: 'software-engineering-pro-21553.appspot.com',
    measurementId: 'G-S0D2JJJ3CN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZtCBYoDYgdImF8XU4tTv3JHCTtA8pnHg',
    appId: '1:1068725299615:android:27f8b9c791626b0875b5aa',
    messagingSenderId: '1068725299615',
    projectId: 'software-engineering-pro-21553',
    storageBucket: 'software-engineering-pro-21553.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBh4PULD9dDp6HnOeIHhErbUAz_o8c8l48',
    appId: '1:1068725299615:ios:46cd4a27a8bbc60875b5aa',
    messagingSenderId: '1068725299615',
    projectId: 'software-engineering-pro-21553',
    storageBucket: 'software-engineering-pro-21553.appspot.com',
    androidClientId: '1068725299615-l7se6md30di9l2gecco6bt2n0c5lu64m.apps.googleusercontent.com',
    iosClientId: '1068725299615-cv9qpro5dq1rknj2all84hletuln8vfd.apps.googleusercontent.com',
    iosBundleId: 'com.santhosh.softwareEnggProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBh4PULD9dDp6HnOeIHhErbUAz_o8c8l48',
    appId: '1:1068725299615:ios:46cd4a27a8bbc60875b5aa',
    messagingSenderId: '1068725299615',
    projectId: 'software-engineering-pro-21553',
    storageBucket: 'software-engineering-pro-21553.appspot.com',
    androidClientId: '1068725299615-l7se6md30di9l2gecco6bt2n0c5lu64m.apps.googleusercontent.com',
    iosClientId: '1068725299615-cv9qpro5dq1rknj2all84hletuln8vfd.apps.googleusercontent.com',
    iosBundleId: 'com.santhosh.softwareEnggProject',
  );
}
